time-changed-msg: " &e→ &2It's now day time, thanks to &a%player%&2 for sleeping!"
weather-changed-msg: " &e→ &3The weather is now clear, thanks to &b%player%&3 for sleeping!"

already-day-msg: " &e→ &4It's already day time, &c%player%&4."

stop-entering-bed: "true"